apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-application
  labels:
    app: demo-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-application
  template:
    metadata:
      labels:
        app: demo-application
    spec:
      containers:
      - name: demo-application
        image: 10.26.8.89:5000/demo-application
        ports:
        - containerPort: 9090